# Generated by Django 5.2.8 on 2025-11-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_hospital_centralauthmodel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centralclientassignment',
            unique_together={('client',)},
        ),
        migrations.RemoveField(
            model_name='centralclientassignment',
            name='central_model',
        ),
    ]
